name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          # Скачиваем файл
          curl -L -o app.deb "${{ github.event.inputs.deb }}"
          
          # Распаковываем
          mkdir temp_deb
          dpkg-deb -x app.deb temp_deb
          
          # Создаем структуру IPA
          mkdir -p Payload
          
          # Ищем приложение
          APP_PATH=$(find temp_deb -name "*.app" -type d | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "ОШИБКА: Папка .app не найдена!"
            exit 1
          fi
          
          cp -R "$APP_PATH" Payload/
          
          # Собираем
          zip -r App.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: App.ipa
