name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          curl -L -o app.deb "${{ github.event.inputs.deb }}"
          mkdir temp_deb
          dpkg-deb -x app.deb temp_deb
          
          echo "--- СПИСОК ВСЕХ ПАПОК ВНУТРИ ---"
          find temp_deb -type d
